export default {
  MONGODB_HOST: process.env.MONGODB_HOST,
  MONGODB_PORT: process.env.MONGODB_PORT,
  MONGODB_USER: process.env.MONGODB_USER,
  MONGODB_PASSWORD: process.env.MONGODB_PASSWORD,
  MONGODB_DB_NAME: process.env.MONGODB_DB_NAME,
  MONGODB_DB_DEV_NAME: process.env.MONGODB_DB_DEV_NAME,
}
